api_platform:
    title: eos.uptrade Battleship API
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    # Arachnophobia mode: https://github.com/api-platform/core/pull/2247
    show_webby: false

    # Eine einsteigerfreundlichere Startseite zeigen. Die von API Platform generierte Autodokumentation wird in 
    # routes.yaml unter /api_entrypoint angeboten.
    enable_entrypoint: false
